# Generated by Django 5.0.6 on 2024-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mythic', '0002_task_children_task_preceding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='children',
            field=models.ManyToManyField(blank=True, to='Mythic.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='preceding',
            field=models.ManyToManyField(blank=True, to='Mythic.task'),
        ),
    ]
