# Generated by Django 5.0.6 on 2024-08-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mythic', '0003_alter_task_children_alter_task_preceding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='children',
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Mythic.task'),
        ),
    ]
