# Generated by Django 5.0.6 on 2024-08-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mythic', '0005_remove_task_preceding_task_previous_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='previous_task',
        ),
        migrations.AddField(
            model_name='task',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_task', to='Mythic.task'),
        ),
    ]
