# Generated by Django 5.0.6 on 2024-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mythic', '0006_remove_task_previous_task_task_is_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='next_task',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
