# Generated by Django 5.0.6 on 2024-08-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mythic', '0007_remove_task_next_task_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_task', to='Mythic.task'),
        ),
    ]
