# Generated by Django 5.0.6 on 2024-08-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mythic', '0008_task_next_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='next_task',
        ),
    ]
